<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create([ "state_id"   =>  2, "name"   =>	"MEDELLÍN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ABEJORRAL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ABRIAQUÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ALEJANDRÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"AMAGÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"AMALFI" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ANDES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ANGELÓPOLIS", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ANGOSTURA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ANORÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SANTA FÉ DE ANTIOQUIA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ANZÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"APARTADÓ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ARBOLETES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ARGELIA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ARMENIA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"BARBOSA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"BELMIRA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"BELLO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"BETANIA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"BETULIA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CIUDAD BOLÍVAR" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"BRICEÑO", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"BURITICÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CÁCERES", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CAICEDO", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CALDAS" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CAMPAMENTO" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CAÑASGORDAS", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CARACOLÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CARAMANTA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CAREPA" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"EL CARMEN DE VIBORAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CAROLINA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CAUCASIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CHIGORODÓ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CISNEROS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"COCORNÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CONCEPCIÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"CONCORDIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"COPACABANA" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"DABEIBA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"DONMATÍAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"EBÉJICO", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"EL BAGRE"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ENTRERRÍOS", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ENVIGADO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"FREDONIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"FRONTINO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"GIRALDO"   , "active" => 1]);
        City::create([ "state_id"   =>  2, "name"   =>	"GIRARDOTA" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"GÓMEZ PLATA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"GRANADA ",     "active" => 1]);
        City::create([ "state_id"   =>  2, "name"   =>	"GUADALUPE" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"GUARNE", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"GUATAPÉ",  "active" => 1]);
        City::create([ "state_id"   =>  2, "name"   =>	"HELICONIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"HISPANIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ITAGÜÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ITUANGO" ,"active" => 1]);
        City::create([ "state_id"   =>  2, "name"   =>	"JARDÍN", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"JERICÓ", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"LA CEJA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"LA ESTRELLA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"LA PINTADA" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"LA UNIÓN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"LIBORINA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"MACEO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"MARINILLA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"MONTEBELLO" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"MURINDÓ", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"MUTATÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"NARIÑO" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"NECOCLÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"NECHÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"OLAYA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"PEÑOL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"PEQUE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"PUEBLORRICO", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"PUERTO BERRÍO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"PUERTO NARE", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"PUERTO TRIUNFO" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"REMEDIOS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"RETIRO" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"RIONEGRO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SABANALARGA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SABANETA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SALGAR" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN ANDRÉS DE CUERQUÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN CARLOS" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN FRANCISCO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN JERÓNIMO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN JOSÉ DE LA MONTAÑA" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN JUAN DE URABÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN LUIS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN PEDRO DE LOS MILAGROS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN PEDRO DE URABÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN RAFAEL" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN ROQUE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SAN VICENTE FERRER" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SANTA BÁRBARA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SANTA ROSA DE OSOS" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SANTO DOMINGO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"EL SANTUARIO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SEGOVIA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SONSÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"SOPETRÁN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"TÁMESIS", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"TARAZÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"TARSO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"TITIRIBÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"TOLEDO" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"TURBO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"URAMITA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"URRAO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"VALDIVIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"VALPARAÍSO" , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"VEGACHÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"VENECIA", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"VIGÍA DEL FUERTE"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"YALÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"YARUMAL", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"YOLOMBÓ", "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"YONDÓ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  2, "name"   =>	"ZARAGOZA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"BARRANQUILLA" , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"BARANOA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"CAMPO DE LA CRUZ" , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"CANDELARIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"GALAPA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"JUAN DE ACOSTA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"LURUACO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"MALAMBO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"MANATÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"PALMAR DE VARELA" , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"PIOJÓ", "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"POLONUEVO", "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"PONEDERA" , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"PUERTO COLOMBIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"REPELÓN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"SABANAGRANDE" , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"SABANALARGA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"SANTA LUCÍA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"SANTO TOMÁS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"SOLEDAD"  , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"SUAN" , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"TUBARÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  4, "name"   => 	"USIACURÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  5, "name"   =>  "BOGOTÁ, D.C.", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>  "CARTAGENA DE INDIAS"   , "active" => 1]);
        City::create([ "state_id"   =>  6, "name"   =>   "ACHÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "ALTOS DEL ROSARIO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "ARENAL", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "ARJONA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "ARROYOHONDO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "BARRANCO DE LOBA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "CALAMAR", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "CANTAGALLO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "CICUCO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "CÓRDOBA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "CLEMENCIA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "EL CARMEN DE BOLÍVAR", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "EL GUAMO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "EL PEÑÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "HATILLO DE LOBA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "MAGANGUÉ", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "MAHATES", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "MARGARITA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "MARÍA LA BAJA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "MONTECRISTO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "MOMPÓS", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "MORALES", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "NOROSÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "PINILLOS", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "REGIDOR", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "RÍO VIEJO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SAN CRISTÓBAL", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SAN ESTANISLAO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SAN FERNANDO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SAN JACINTO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SAN JACINTO DEL CAUCA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SAN JUAN NEPOMUCENO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SAN MARTÍN DE LOBA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SAN PABLO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SANTA CATALINA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SANTA ROSA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SANTA ROSA DEL SUR", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SIMITÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "SOPLAVIENTO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "TALAIGUA NUEVO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "TIQUISIO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "TURBACO", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "TURBANÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "VILLANUEVA", "active" => 1 ]);
        City::create([ "state_id"   =>  6, "name"   =>   "ZAMBRANO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "TUNJA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "ALMEIDA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "AQUITANIA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "ARCABUCO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "BELÉN", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "BERBEO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "BETÉITIVA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "BOAVITA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "BOYACÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "BRICEÑO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "BUENAVISTA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "BUSBANZÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CALDAS", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CAMPOHERMOSO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CERINZA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CHINAVITA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CHIQUINQUIRÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CHISCAS", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CHITA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CHITARAQUE", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CHIVATÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CIÉNEGA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CÓMBITA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "COPER", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CORRALES", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "COVARACHÍA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CUBARÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CUCAITA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CUÍTIVA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CHÍQUIZA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "CHIVOR", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "DUITAMA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "EL COCUY", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "EL ESPINO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "FIRAVITOBA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "FLORESTA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>   "GACHANTIVÁ"   , "active" => 1]);
        City::create([ "state_id"   =>  7, "name"   =>	 "GÁMEZA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "GARAGOA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "GUACAMAYAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "GUATEQUE", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "GUAYATÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "GÜICÁN DE LA SIERRA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "IZA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "JENESANO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "JERICÓ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "LABRANZAGRANDE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "LA CAPILLA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "LA VICTORIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "LA UVITA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "VILLA DE LEYVA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "MACANAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "MARIPÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "MIRAFLORES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "MONGUA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "MONGUÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "MONIQUIRÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "MOTAVITA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "MUZO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "NOBSA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "NUEVO COLÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "OICATÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "OTANCHE" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PACHAVITA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PÁEZ", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PAIPA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PAJARITO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PANQUEBA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PAUNA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PAYA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PAZ DE RÍO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PESCA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PISBA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "PUERTO BOYACÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "QUÍPAMA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "RAMIRIQUÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "RÁQUIRA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "RONDÓN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SABOYÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SÁCHICA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SAMACÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SAN EDUARDO" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SAN JOSÉ DE PARE", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SAN LUIS DE GACENO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SAN MATEO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SAN MIGUEL DE SEMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SAN PABLO DE BORBUR" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SANTANA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SANTA MARÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SANTA ROSA DE VITERBO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SANTA SOFÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SATIVANORTE" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SATIVASUR"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SIACHOQUE"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SOATÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SOCOTÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SOCHA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SOGAMOSO", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SOMONDOCO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SORA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SOTAQUIRÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SORACÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SUSACÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SUTAMARCHÁN" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "SUTATENZA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TASCO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TENZA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TIBANÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TIBASOSA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TINJACÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TIPACOQUE"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TOCA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TOGÜÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TÓPAGA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TOTA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TUNUNGUÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TURMEQUÉ", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TUTA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "TUTAZÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "ÚMBITA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "VENTAQUEMADA", "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "VIRACACHÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  7, "name"   =>	 "ZETAQUIRA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"MANIZALES", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"AGUADAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"ANSERMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"ARANZAZU" , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"BELALCÁZAR"   , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"CHINCHINÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"FILADELFIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"LA DORADA", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"LA MERCED", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"MANZANARES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"MARMATO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"MARQUETALIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"MARULANDA", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"NEIRA", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"NORCASIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   =>  "CALDAS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"PÁCORA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"PALESTINA", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"PENSILVANIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"RIOSUCIO" , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"RISARALDA", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"SALAMINA" , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"SAMANÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"SAN JOSÉ" , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"SUPÍA", "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"VICTORIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"VILLAMARÍA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  8, "name"   => 	"VITERBO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"FLORENCIA", "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"ALBANIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"BELÉN DE LOS ANDAQUÍES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"CARTAGENA DEL CHAIRÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"CURILLO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"EL DONCELLO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"EL PAUJÍL", "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"LA MONTAÑITA" , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"MILÁN", "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"MORELIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"PUERTO RICO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"SAN JOSÉ DEL FRAGUA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"SAN VICENTE DEL CAGUÁN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"SOLANO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"SOLITA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  9, "name"   => 	"VALPARAÍSO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"POPAYÁN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"ALMAGUER" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"ARGELIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"BALBOA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"BOLÍVAR"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"BUENOS AIRES" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"CAJIBÍO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"CALDONO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"CALOTO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"CORINTO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"EL TAMBO" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"FLORENCIA", "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"GUACHENÉ" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"GUAPÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"INZÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"JAMBALÓ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"LA SIERRA", "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"LA VEGA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"LÓPEZ DE MICAY"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"MERCADERES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"MIRANDA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"MORALES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"PADILLA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"PÁEZ" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"PATÍA", "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"PIAMONTE" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"PIENDAMÓ – TUNÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"PUERTO TEJADA", "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"PURACÉ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"ROSAS", "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"SAN SEBASTIÁN", "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"SANTANDER DE QUILICHAO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"SANTA ROSA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"SILVIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"SOTARA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"SUÁREZ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"SUCRE", "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"TIMBÍO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"TIMBIQUÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"TORIBÍO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"TOTORÓ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  11, "name"   => 	"VILLA RICA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"VALLEDUPAR"   , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"AGUACHICA", "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"AGUSTÍN CODAZZI"  , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"ASTREA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"BECERRIL" , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"BOSCONIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"CHIMICHAGUA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"CHIRIGUANÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"CURUMANÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"EL COPEY" , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"EL PASO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"GAMARRA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"GONZÁLEZ" , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"LA GLORIA", "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"LA JAGUA DE IBIRICO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"MANAURE BALCÓN DEL CESAR" , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"PAILITAS" , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"PELAYA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"PUEBLO BELLO" , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"RÍO DE ORO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"LA PAZ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"SAN ALBERTO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"SAN DIEGO", "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"SAN MARTÍN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  12, "name"   => 	"TAMALAMEQUE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"MONTERÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"AYAPEL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"BUENAVISTA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"CANALETE" , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"CERETÉ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"CHIMÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"CHINÚ", "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"CIÉNAGA DE ORO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"COTORRA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"LA APARTADA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"LORICA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"LOS CÓRDOBAS" , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"MOMIL", "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"MONTELÍBANO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"MOÑITOS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"PLANETA RICA" , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"PUEBLO NUEVO" , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"PUERTO ESCONDIDO" , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"PUERTO LIBERTADOR", "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"PURÍSIMA DE LA CONCEPCIÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"SAHAGÚN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"SAN ANDRÉS DE SOTAVENTO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"SAN ANTERO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"SAN BERNARDO DEL VIENTO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"SAN CARLOS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"SAN JOSÉ DE URÉ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"SAN PELAYO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"TIERRALTA", "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"TUCHÍN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  14, "name"   => 	"VALENCIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"AGUA DE DIOS" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"ALBÁN", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"ANAPOIMA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"ANOLAIMA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"ARBELÁEZ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"BELTRÁN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"BITUIMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"BOJACÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CABRERA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CACHIPAY" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CAJICÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CAPARRAPÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CÁQUEZA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CARMEN DE CARUPA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CHAGUANÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CHÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CHIPAQUE" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CHOACHÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CHOCONTÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"COGUA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"COTA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"CUCUNUBÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"EL COLEGIO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"EL PEÑÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"EL ROSAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"FACATATIVÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"FÓMEQUE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"FOSCA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"FUNZA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"FÚQUENE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"FUSAGASUGÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GACHALÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"	=>  "GACHANCIPÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GACHETÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GAMA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GIRARDOT" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GRANADA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GUACHETÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GUADUAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GUASCA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GUATAQUÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GUATAVITA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GUAYABAL DE SÍQUIMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GUAYABETAL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"GUTIÉRREZ", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"JERUSALÉN", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"JUNÍN", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"LA CALERA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"LA MESA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"LA PALMA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"LA PEÑA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"LA VEGA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"LENGUAZAQUE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"MACHETÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"MADRID"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"MANTA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"MEDINA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"MOSQUERA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"NARIÑO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"NEMOCÓN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"NILO" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"NIMAIMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"NOCAIMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"VENECIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"PACHO", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"PAIME", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"PANDI", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"PARATEBUENO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"PASCA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"PUERTO SALGAR", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"PULÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"QUEBRADANEGRA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"QUETAME"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"QUIPILE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"APULO", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"RICAURTE" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SAN ANTONIO DEL TEQUENDAMA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SAN BERNARDO" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SAN CAYETANO" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SAN FRANCISCO", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SAN JUAN DE RIOSECO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SASAIMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SESQUILÉ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SIBATÉ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SILVANIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SIMIJACA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SOACHA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SOPÓ" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SUBACHOQUE"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SUESCA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SUPATÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SUSA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"SUTATAUSA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TABIO", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TAUSA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TENA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TENJO", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TIBACUY"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TIBIRITA" , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TOCAIMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TOCANCIPÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"TOPAIPÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"UBALÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"UBAQUE"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"VILLA DE SAN DIEGO DE UBATÉ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"UNE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"ÚTICA", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"VERGARA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"VIANÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"VILLAGÓMEZ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"VILLAPINZÓN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"VILLETA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"VIOTÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"YACOPÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"ZIPACÓN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  33, "name"   => 	"ZIPAQUIRÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"QUIBDÓ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"ACANDÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"ALTO BAUDÓ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"ATRATO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"BAGADÓ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"BAHÍA SOLANO" , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"BAJO BAUDÓ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"BOJAYÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"EL CANTÓN DEL SAN PABLO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"CARMEN DEL DARIÉN", "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"CÉRTEGUI" , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"CONDOTO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"EL CARMEN DE ATRATO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"EL LITORAL DEL SAN JUAN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"ISTMINA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"JURADÓ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"LLORÓ", "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"MEDIO ATRATO" , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"MEDIO BAUDÓ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"MEDIO SAN JUAN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"NÓVITA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"NUQUÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"RÍO IRÓ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"RÍO QUITO", "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"RIOSUCIO" , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"SAN JOSÉ DEL PALMAR"  , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"SIPÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"TADÓ" , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"UNGUÍA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  13, "name"   => 	"UNIÓN PANAMERICANA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"NEIVA", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"ACEVEDO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"AGRADO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"AIPE" , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"ALGECIRAS", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"ALTAMIRA" , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"BARAYA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"CAMPOALEGRE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"COLOMBIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"ELÍAS", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"GARZÓN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"GIGANTE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"GUADALUPE", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"HOBO" , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"ÍQUIRA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"ISNOS", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"LA ARGENTINA" , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"LA PLATA" , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"NÁTAGA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"OPORAPA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"PAICOL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"PALERMO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"PALESTINA", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"PITAL", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"PITALITO" , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"RIVERA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"SALADOBLANCO" , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"SAN AGUSTÍN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"SANTA MARÍA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"SUAZA", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"TARQUI"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"TESALIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"TELLO", "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"TERUEL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"TIMANÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"VILLAVIEJA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  17, "name"   => 	"YAGUARÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"RIOHACHA" , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"ALBANIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"BARRANCAS", "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"DIBULLA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"DISTRACCIÓN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"EL MOLINO", "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"FONSECA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"HATONUEVO", "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"LA JAGUA DEL PILAR"   , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"MAICAO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"MANAURE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"SAN JUAN DEL CESAR"   , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"URIBIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"URUMITA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  18, "name"   => 	"VILLANUEVA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"SANTA MARTA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"ALGARROBO", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"ARACATACA", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"ARIGUANÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"CERRO DE SAN ANTONIO" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"CHIVOLO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"CIÉNAGA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"CONCORDIA", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"EL BANCO" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"EL PIÑÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"EL RETÉN" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"FUNDACIÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"GUAMAL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"NUEVA GRANADA", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"PEDRAZA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"PIJIÑO DEL CARMEN", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"PIVIJAY"  , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"PLATO", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   => 	"PUEBLOVIEJO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "REMOLINO" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "SABANAS DE SAN ÁNGEL" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "SALAMINA" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "SAN SEBASTIÁN DE BUENAVISTA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "SAN ZENÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "SANTA ANA", "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "SANTA BÁRBARA DE PINTO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "SITIONUEVO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "TENERIFE" , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "ZAPAYÁN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  19, "name"   =>  "ZONA BANANERA", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "VILLAVICENCIO", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "ACACÍAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "BARRANCA DE UPÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "CABUYARO" , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "CASTILLA LA NUEVA", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "CUBARRAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "CUMARAL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "EL CALVARIO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "EL CASTILLO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "EL DORADO", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "FUENTEDEORO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "GRANADA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "GUAMAL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "MAPIRIPÁN", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "MESETAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "LA MACARENA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "URIBE", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "LEJANÍAS" , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "PUERTO CONCORDIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "PUERTO GAITÁN", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "PUERTO LÓPEZ" , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "PUERTO LLERAS", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "PUERTO RICO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "RESTREPO" , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "SAN CARLOS DE GUAROA" , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "SAN JUAN DE ARAMA", "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "SAN JUANITO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "SAN MARTÍN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  20, "name"   =>  "VISTAHERMOSA" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   =>  "PASTO" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   =>  "ALBÁN" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   =>  "ALDANA", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   =>  "ANCUYÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"ARBOLEDA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"BARBACOAS" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"BELÉN" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"BUESACO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"COLÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"CONSACÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"CONTADERO" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"CÓRDOBA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"CUASPÚD"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"CUMBAL", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"CUMBITARA" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"CHACHAGÜÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"CHARCO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"PEÑOL", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"ROSARIO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"TABLÓN DE GÓMEZ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"TAMBO", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"TUNES" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"GUACHUCAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"GUAITARILLA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"GUALMATÁN" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"ILES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"IMUÉS" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"IPIALES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"LA CRUZ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"LA FLORIDA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"LA LLANADA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"LA TOLA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"LA UNIÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"LEIVA" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"LINARES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"LOS ANDES" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"MAGÜÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"MALLAMA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"MOSQUERA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"NARIÑO", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"OLAYA HERRERA" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"OSPINA", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"FRANCISCO PIZARRO" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"POLICARPA" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"POTOSÍ", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"PROVIDENCIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"PUERRES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"PUPIALES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"RICAURTE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"ROBERTO PAYÁN" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SAMANIEGO" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SANDONÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SAN BERNARDO" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SAN LORENZO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SAN PABLO", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SAN PEDRO DE CARTAGO" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SANTA BÁRBARA", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SANTACRUZ" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SAPUYES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SAMINANGO" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SANGUA", "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"SAN ANDRÉS DE TUMACO" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"TÚQUERRES" , "active" => 1 ]);
        City::create([ "state_id"   =>  21, "name"   => 	"YACUANQUER", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "CÚCUTA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "ÁBREGO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "ARBOLEDAS", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "BOCHALEMA", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "BUCARASICA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "CÁCOTA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "CÁCHIRA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "CHINÁCOTA", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "CHITAGÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "CONVENCIÓN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "CUCUTILLA", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "DURANIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "EL CARMEN", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "EL TARRA" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "EL ZULIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "GRAMALOTE", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "HACARÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "HERRÁN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "LABATECA" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "LA ESPERANZA" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "LA PLAYA" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "LOS PATIOS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "LOURDES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "MUTISCUA" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "OCAÑA", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "PAMPLONA" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "PAMPLONITA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "PUERTO SANTANDER" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "RAGONVALIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "SALAZAR"  , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "SAN CALIXTO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "SAN CAYETANO" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "SANTIAGO" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "SARDINATA", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "SILOS", "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "TEORAMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "TIBÚ" , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "TOLEDO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "VILLA CARO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  22, "name"   =>  "VILLA DEL ROSARIO", "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   =>  "ARMENIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   =>  "BUENAVISTA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   =>  "CALARCÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   =>  "CIRCASIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   => 	"CÓRDOBA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   => 	"FILANDIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   => 	"GÉNOVA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   => 	"LA TEBAIDA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   => 	"MONTENEGRO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   => 	"PIJAO", "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   => 	"QUIMBAYA" , "active" => 1 ]);
        City::create([ "state_id"   =>  24, "name"   => 	"SALENTO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"PEREIRA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"APÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"BALBOA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"BELÉN DE UMBRÍA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"DOSQUEBRADAS" , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"GUÁTICA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"LA CELIA" , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"LA VIRGINIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"MARSELLA" , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"MISTRATÓ" , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"PUEBLO RICO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"QUINCHÍA" , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"SANTA ROSA DE CABAL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  25, "name"   => 	"SANTUARIO", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"BUCARAMANGA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"AGUADA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"ALBANIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"ARATOCA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"BARBOSA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"BARICHARA", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"BARRANCABERMEJA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"BETULIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"BOLÍVAR"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CABRERA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CALIFORNIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CAPITANEJO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CARCASÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CEPITÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CERRITO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CHARALÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CHARTA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CHIMA", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CHIPATÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CIMITARRA", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CONCEPCIÓN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CONFINES" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CONTRATACIÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"COROMORO" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"CURITÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"EL CARMEN DE CHUCURÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"EL GUACAMAYO" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"EL PEÑÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"EL PLAYÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"ENCINO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"ENCISO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"FLORIÁN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"FLORIDABLANCA", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"GALÁN", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"GÁMBITA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"GIRÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"GUACA", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"GUADALUPE", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"GUAPOTÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"GUAVATÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"GÜEPSA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"HATO" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"JESÚS MARÍA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"JORDÁN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"LA BELLEZA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"LANDÁZURI", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"LA PAZ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"LEBRIJA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"LOS SANTOS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"MACARAVITA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"MÁLAGA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"MATANZA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"MOGOTES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"MOLAGAVITA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"OCAMONTE" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"OIBA" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"ONZAGA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"PALMAR"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"PALMAS DEL SOCORRO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"PÁRAMO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"PIEDECUESTA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"PINCHOTE" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"PUENTE NACIONAL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"PUERTO PARRA" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"PUERTO WILCHES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"RIONEGRO" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SABANA DE TORRES" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SAN ANDRÉS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SAN BENITO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SAN GIL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SAN JOAQUÍN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SAN JOSÉ DE MIRANDA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SAN MIGUEL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SAN VICENTE DE CHUCURÍ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SANTA BÁRBARA", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SANTA HELENA DEL OPÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SIMACOTA" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SOCORRO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SUAITA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SUCRE", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"SURATÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"TONA" , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"VALLE DE SAN JOSÉ", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"VÉLEZ", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"VETAS", "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"VILLANUEVA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  27, "name"   => 	"ZAPATOCA" , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SINCELEJO", "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"BUENAVISTA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"CAIMITO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"COLOSÓ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"COROZAL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"COVEÑAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"CHALÁN"   , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"EL ROBLE" , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"GALERAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"GUARANDA" , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"LA UNIÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"LOS PALMITOS" , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"MAJAGUAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"MORROA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"OVEJAS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"PALMITO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SAMPUÉS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SAN BENITO ABAD"  , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SAN JUAN DE BETULIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SAN MARCOS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SAN ONOFRE"   , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SAN PEDRO", "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SAN LUIS DE SINCÉ", "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SUCRE", "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"SANTIAGO DE TOLÚ" , "active" => 1 ]);
        City::create([ "state_id"   =>  28, "name"   => 	"TOLÚ VIEJO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"IBAGUÉ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"ALPUJARRA", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"ALVARADO" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"AMBALEMA" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"ANZOÁTEGUI"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"ARMERO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"ATACO", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"CAJAMARCA", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"CARMEN DE APICALÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"CASABIANCA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"CHAPARRAL", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"   => 	"COELLO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "COYAIMA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "CUNDAY"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "DOLORES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "ESPINAL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "FALAN", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "FLANDES"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "FRESNO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "GUAMO", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "HERVEO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "HONDA", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "ICONONZO" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "LÉRIDA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "LÍBANO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "SAN SEBASTIÁN DE MARIQUITA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "MELGAR"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "MURILLO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "NATAGAIMA", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "ORTEGA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "PALOCABILDO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "PIEDRAS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "PLANADAS" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "PRADO", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "PURIFICACIÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "RIOBLANCO", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "RONCESVALLES" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "ROVIRA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "SALDAÑA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "SAN ANTONIO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "SAN LUIS" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "SANTA ISABEL" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "SUÁREZ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "VALLE DE SAN JUAN", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "VENADILLO", "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "VILLAHERMOSA" , "active" => 1 ]);
        City::create([ "state_id"   =>  29, "name"	=>  "VILLARRICA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "CALI" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "ALCALÁ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "ANDALUCÍA", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "ANSERMANUEVO" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "ARGELIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "BOLÍVAR"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "BUENAVENTURA" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "GUADALAJARA DE BUGA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "BUGALAGRANDE" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "CAICEDONIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "CALIMA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "CANDELARIA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "CARTAGO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "DAGUA", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "EL ÁGUILA", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "EL CAIRO" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "EL CERRITO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "EL DOVIO" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "FLORIDA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "GINEBRA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "GUACARÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "JAMUNDÍ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "LA CUMBRE", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "LA UNIÓN" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "LA VICTORIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "OBANDO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "PALMIRA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "PRADERA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "RESTREPO" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "RIOFRÍO"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "ROLDANILLO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "SAN PEDRO", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "SEVILLA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "TORO" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "TRUJILLO" , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "TULUÁ", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "ULLOA", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "VERSALLES", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "VIJES", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "YOTOCO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "YUMBO", "active" => 1 ]);
        City::create([ "state_id"   =>  30, "name"	=>  "ZARZAL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  3, "name"	=>  "ARAUCA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  3, "name"	=>  "ARAUQUITA", "active" => 1 ]);
        City::create([ "state_id"   =>  3, "name"	=>  "CRAVO NORTE"  , "active" => 1 ]);
        City::create([ "state_id"   =>  3, "name"	=>  "FORTUL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  3, "name"	=>  "PUERTO RONDÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  3, "name"	=>  "SARAVENA" , "active" => 1 ]);
        City::create([ "state_id"   =>  3, "name"	=>  "TAME" , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "YOPAL", "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "AGUAZUL"  , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "CHÁMEZA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "HATO COROZAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "LA SALINA", "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "MANÍ" , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "MONTERREY", "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "NUNCHÍA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "OROCUÉ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "PAZ DE ARIPORO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "PORE" , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "RECETOR"  , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "SABANALARGA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "SÁCAMA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "SAN LUIS DE PALENQUE" , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "TÁMARA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "TAURAMENA", "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "TRINIDAD" , "active" => 1 ]);
        City::create([ "state_id"   =>  10, "name"	=>  "VILLANUEVA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "MOCOA", "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "COLÓN", "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "ORITO", "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "PUERTO ASÍS"  , "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "PUERTO CAICEDO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "PUERTO GUZMÁN", "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "PUERTO LEGUÍZAMO" , "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "SIBUNDOY" , "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "SAN FRANCISCO", "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "SAN MIGUEL"   , "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "SANTIAGO" , "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "VALLE DEL GUAMUEZ", "active" => 1 ]);
        City::create([ "state_id"   =>  23, "name"	=>  "VILLAGARZÓN"  , "active" => 1 ]);
        City::create([ "state_id"   =>  26, "name"	=>  "SAN ANDRÉS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  26, "name"	=>  "PROVIDENCIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "LETICIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "EL ENCANTO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "LA CHORRERA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "LA PEDRERA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "LA VICTORIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "MIRITÍ – PARANÁ"  , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "PUERTO ALEGRÍA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "PUERTO ARICA" , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "PUERTO NARIÑO", "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "PUERTO SANTANDER" , "active" => 1 ]);
        City::create([ "state_id"   =>  1, "name"	=>  "TARAPACÁ" , "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "INÍRIDA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "BARRANCO MINAS"   , "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "MAPIRIPANA"   , "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "SAN FELIPE"   , "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "PUERTO COLOMBIA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "LA GUADALUPE" , "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "CACAHUAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "PANA PANA", "active" => 1 ]);
        City::create([ "state_id"   =>  15, "name"	=>  "MORICHAL" , "active" => 1 ]);
        City::create([ "state_id"   =>  16, "name"	=>  "SAN JOSÉ DEL GUAVIARE", "active" => 1 ]);
        City::create([ "state_id"   =>  16, "name"	=>  "CALAMAR"  , "active" => 1 ]);
        City::create([ "state_id"   =>  16, "name"	=>  "EL RETORNO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  16, "name"	=>  "MIRAFLORES"   , "active" => 1 ]);
        City::create([ "state_id"   =>  31, "name"	=>  "MITÚ" , "active" => 1 ]);
        City::create([ "state_id"   =>  31, "name"	=>  "CARURÚ"   , "active" => 1 ]);
        City::create([ "state_id"   =>  31, "name"	=>  "PACOA", "active" => 1 ]);
        City::create([ "state_id"   =>  31, "name"	=>  "TARAIRA"  , "active" => 1 ]);
        City::create([ "state_id"   =>  31, "name"	=>  "PAPUNAHUA", "active" => 1 ]);
        City::create([ "state_id"   =>  31, "name"	=>  "YAVARATÉ" , "active" => 1 ]);
        City::create([ "state_id"   =>  32, "name"	=>  "PUERTO CARREÑO"   , "active" => 1 ]);
        City::create([ "state_id"   =>  32, "name"	=>  "LA PRIMAVERA" , "active" => 1 ]);
        City::create([ "state_id"   =>  32, "name"	=>  "SANTA ROSALÍA", "active" => 1 ]);
        City::create([ "state_id"   =>  32, "name"	=>  "CUMARIBO" , "active" => 1 ]);
    }
}
